leftnav:
- identifier: 7e86551c-d553-4977-8257-a8548c876c92
  name: Lecture Notes
  pageRef: /lists/lecture-notes
  weight: 10
- identifier: adcce142-7aa0-4210-bdb3-a379dbfc496a
  name: Solutions
  pageRef: /lists/solutions
  weight: 20
